---
# tasks file for nginx
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install nginx latest version
  ansible.builtin.apt:
    name: nginx
