# переделать под ubuntu 24, там нет версии 18 сделать через добавление репы:
#curl https://nginx.org/keys/nginx_signing.key | sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/nginx.gpg
#echo "deb https://nginx.org/packages/ubuntu $(lsb_release -cs) nginx" | sudo tee /etc/apt/sources.list.d/nginx.list
#sudo apt update
---
# tasks file for nginx
- name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600

- name: Install nginx 1.18 version
  ansible.builtin.apt:
    # name: nginx
    name: nginx=1.18.0-6ubuntu14.6
