---
# install_joomla.yml
- name: Install joomla
  hosts: all
  become: true
  vars:
# этот адрес указан,вместо имени сайта, в /etc/nginx/sites-available/joomla.conf
    joomla_ip: 192.168.0.85
    joomla_folder: /var/www/sites/joomla
    joomla_nginx_config_file: /etc/nginx/sites-available/joomla.conf
    nginx_user: www-data

  gather_facts: true

  roles:
    - role: nginx
    - role: php
    - role: mysql
    - role: joomla
    - role: initapps
